Feat: feedback endpoint
tabiya-tech/compass pull request #282
Opened 2024-11-18 11:39 UTC by Fidesnoella

2024-11-19 09:18 UTC, rav3n11 requested changes

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +    selected_options: Optional[List[str]] = None
selected options should come from an enum... Which means it will have to be serialized and deserialized, same as something like the AgentDirectorState

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +    comment: Optional[str] = None
we should add max-lengths to the fields so that the users cant push an absurdly long answer

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +    comment: Optional[str] = None
perhaps something like 

`comment: Optional[str] = Field(default=None, max_length=4000)`

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +    comment: Optional[str] = None
we can consider a similar thing for the other fields as well... but for the comment I think its necessary

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/routes.py
> +    Add all routes related to user feedback to the FastAPI app.
doc should be improved here right?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/routes.py
> +    router = APIRouter(prefix="/users/feedback", tags=["users-feedback"])
If we want this to be under /users we should add it to the router in the users directory, rather than adding a prefix here...

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/routes.py
> +    router = APIRouter(prefix="/users/feedback", tags=["users-feedback"])
an example is how we do it for add_user_preference_routes(users_router, authentication)

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +from pydantic import BaseModel, Field
Why not put these in the types.py? Why split them up?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/routes.py
> +        await user_feedback_service.create_user_feedback(body, user_info)
I think there is a type mismatch here... FeedbackRecordRequest vs FeedbackRecordModel

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            feedback_data = {
we should be constructing a FeedbackRecordModel object instead of generating a dict with all the fields here...

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            feedback_data = {
FeedbackRecordModel(
user_id=body.user_id, 
...
);

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +                "feedback_time": datetime.utcnow()
datetime.utcnow() seems to be deprecated in Python 3.12... Maybe we can go with the idea of setting this time in the class rather than in the object instantiation like we do with the sent_at field in the AgentOutput
`sent_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))`

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            await self.db[Collections.USER_FEEDBACK].insert_one(feedback_data)
Once we construct a FeedbackRecordModel object we can use the .model_dump() method to get the dictionary from it to put into the db

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            await self.db[Collections.USER_FEEDBACK].insert_one(feedback_data)
feedback_data.model_dump()

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            existing_feedback = await self.db[Collections.USER_FEEDBACK].find_one({"session_id": body.session_id})
we should have a repository for this instead of accessing the db collection here manually... like we do with the user_preferences_repository. get...

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +        if "accuracy_relevance" in questions_cache:
why only load the accuracy_relevance question text? was this for testing?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +    version_file_path = Path(__file__).parent.parent.parent / "version" / "version.json"
I dont see a version.json file in the parent.parent.parent directory... am I missing something?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +            questions_data = await load_questions()
what happens if either of these fail? a 500 I assume?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/feedback/types.py
> +    comment: Optional[str] = None
we'll also need a limit on this field... probably

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/preferences.py
> +        db: AsyncIOMotorDatabase) -> GetUsersPreferencesResponse:
can we just change the response of this method? do we not use it anywhere else?

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/preferences.py
> +        db: AsyncIOMotorDatabase) -> GetUsersPreferencesResponse:
Oh. we're extending... I see

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/preferences.py
> +        feedback_sessions = await db[Collections.USER_FEEDBACK].distinct("session_id", {"user_id": user_id})
again... perhaps this should use a repository...

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/routes.py
> +    user_feedback_routes(app, authentication)
if we add the user_feedback_routes to the users router we can skip this...

2024-11-19 09:18 UTC, rav3n11 commented on backend/app/users/types.py
> -
was the create not being used?

2024-11-19 10:25 UTC, rav3n11 requested changes

2024-11-19 10:25 UTC, rav3n11 commented on backend/app/users/feedback/service.py
> +
in case there is a selected_options array, we should also check that the items are part of the config for the specific questionid

2024-11-19 10:25 UTC, rav3n11 commented on backend/app/users/feedback/model.py
> +
we should have a field serializer for the feedback_time field

2024-11-19 10:25 UTC, rav3n11 commented on backend/app/users/types.py
> +    sessions_with_feedback: list[int] = Field(default_factory=list)
we should return a boolean here that is true if the user has submitted feedback for this session

2024-11-19 10:25 UTC, rav3n11 commented on backend/app/users/types.py
> +    sessions_with_feedback: list[int] = Field(default_factory=list)
feedback_submitted: true/false

2024-11-19 14:07 UTC, Fidesnoella commented on backend/app/users/types.py
> -
yes

2024-11-22 15:04 UTC, irumvanselme approved these changes

2024-11-22 15:05 UTC, merged